# Generated by Django 4.0 on 2022-01-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_num',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
