# Generated by Django 4.0 on 2022-04-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Dob',
            field=models.DateField(null=True),
        ),
    ]
