# Generated by Django 4.0 on 2022-01-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_num',
            field=models.IntegerField(default=100),
        ),
    ]
