# Generated by Django 4.0 on 2022-03-03 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('sec', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classs',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='the_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentsforclass', to='user.class'),
        ),
    ]
