# Generated by Django 4.0 on 2022-04-17 18:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.courses'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cnic',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Cnic must be entered in the format: '11111-1111111-1'. Cnic must be entered with dashes.", regex='^[0-9]{5}-[0-9]{7}-[0-9]{1}$')]),
        ),
    ]
