# Generated by Django 4.0 on 2022-01-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='portal',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
