# Generated by Django 4.0 on 2022-04-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_timetable_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='subhoursend',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subhoursstart',
            field=models.TimeField(),
        ),
    ]
