# Generated by Django 4.0 on 2022-04-18 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_assignment_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.faculty'),
        ),
    ]
