# Generated by Django 4.0 on 2022-04-18 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_assignment_class_id_assignment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.class'),
        ),
    ]
