# Generated by Django 4.0 on 2022-01-16 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='id',
        ),
        migrations.AddField(
            model_name='announcement',
            name='Arthur',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='Arthur', serialize=False, to='user.user'),
            preserve_default=False,
        ),
    ]
