# Generated by Django 4.0 on 2022-06-08 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='Arthur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Arthur', to='user.user'),
        ),
    ]
