# Generated by Django 4.0 on 2022-01-16 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('announcements', '0002_remove_announcement_id_announcement_arthur'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='Arthur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Arthur', to='user.user'),
        ),
    ]
